#cloud-config
hostname: <color>
manage_etc_hosts: true
users:
  - name: pirate
    primary-group: users
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users,docker,adm,dialout,audio,plugdev,netdev,video,spi,i2c,gpio
    ssh-import-id: None
    lock_passwd: true
    ssh-authorized-keys:
      - <ssh-key>
write_files:
-   content: |
        {
          "labels": [ "os=linux", "arch=arm" ],
          "experimental": true
        }
    owner: root:root
    path: /etc/docker/daemon.json
runcmd:
 - [ systemctl, restart, avahi-daemon ]
 - [ systemctl, restart, docker ]
